name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Release Version
    uses: CoreWebMicroservices/corems-project/.github/workflows/java-service-release.yml@main
    with:
      service-name: 'user-ms'
      java-version: '25'
      docker-registry: 'ghcr.io'
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      docker-password: ${{ secrets.GITHUB_TOKEN }}
